### PR TITLE
upgrade to libvlc 2.0.1, reenable armeabi

### PR DESCRIPTION
**Pull request by sreichholf**
dunno if you're interested but as i wanted this for my project i thought I'll open a pull request.

### CODE REVIEW

**Comment by rniebecker** [comment]
Hey, why would someone want to support plain armeabi? Unless you want/need to support devices from 2011 which are probably all below api level 19 this is a major waste of apk space. :)

**Comment by sreichholf** [comment]
mostly because my app has minapi 14 :). Besides that you can fix the size issues by using gradles apk split capabilites and split by arch :) (which leavs you with about 12MB/Arch for libvlc).

**Comment by rniebecker** [comment]
I'm actually using the abiFilter instead to only compile the architectures in that I need.

Cheers,
Ralf

**Comment by sreichholf** [comment]
Just as fine and saving quite some Management-Work on the play console

**Comment by FabianTerhorst** [comment]
I have tested your branch. Looks good to me. :+1:

**Comment by pzhangleo** [comment]
fantastic job！

**Comment by xiaodao2** [comment]
I'm a freshman ，where are the sample or decoment? I don't how to put my project ?  please..

**Comment by safakge** [comment]
Works great, thank you! Are you considering pushing this to Maven Central? Mrmaffen doesn't look like he's merging anytime soon..

**Comment by mrmaffen** [comment]
just updated to 2.0.6

**Pull request closed without merging**
